stages:
  data_ingestion:
    cmd: python src/pipeline/stage_01_data_ingestion.py
    deps:
      - src/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/churn_data.csv

  data_transformation:
    cmd: python src/pipeline/stage_02_data_transformation.py
    deps:
      - src/pipeline/stage_02_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/churn_data.csv
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/preprocessor.pkl

  model_trainer:
    cmd: python src/pipeline/stage_03_model_trainer.py
    deps:
      - src/pipeline/stage_03_model_trainer.py
      - src/components/model_trainer.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
    outs:
      - artifacts/model_trainer/model.pkl
    params:
      - LightGBM.n_estimators
      - LightGBM.learning_rate
      - LightGBM.class_weight
  
  model_evaluation:
    cmd: python src/pipeline/stage_04_model_evaluation.py
    deps:
      - src/pipeline/stage_04_model_evaluation.py
      - src/components/model_evaluation.py
      - config/config.yaml
      - artifacts/model_trainer/model.pkl
      - artifacts/data_transformation/test.csv
    outs:
      - artifacts/model_evaluation/metrics.json
