LightGBM:
  valid_name: LightGBM
  n_estimators: 200
  learning_rate: 0.1
  class_weight: balanced
  random_state: 42
  verbosity: -1

mlflow_config:
  experiment_name: "Churn_Prediction_Pipeline"
  model_name: "ChurnPredictionModel"
  target_metric: "f1_score"

model_deployment:
  min_accuracy: 0.40
  min_f1_score: 0.40
  model_name: "ChurnPredictionModel"
  source_stage: "Staging"
  target_stage: "Production"
  archived_stage: "Archived"
  test_data_path: "artifacts/data_transformation/test.csv"
